### ISSUE TITLE
웹에서 녹음한 녹음파일의 북마크가 싱크가 맞지않는다

### ISSUE THREAD

**Issue by stompesi** [HwaYo/LoroClipAndroid#120]
웹에서 녹음한 북마크는 앱에서 보이지않고 (싱크안됨)
앱에서 한 북마크는 웹에서 볼 수 있다.  무슨문제인지는 정확히 모르겠네요

**Comment by angdev** [comment]
북마크 연관 문제였었는데 해결되어 있었습니다 (..)
